[ERROR] Error running: python3 /home/kin/t2-integradora/zeno-travel/fd/fast-downward.py /home/kin/t2-integradora/zeno-travel/domain.pddl /home/kin/t2-integradora/zeno-travel/problem.pddl --landmarks "lm=lm_hm(reasonable_orders=false, only_causal_landmarks=false, disjunctive_landmarks=false, conjunctive_landmarks=true, no_orders=true)" --heuristic "hlm=lmcount(lm)" --search "astar(lmcut())" > /home/kin/t2-integradora/zeno-travel/output.txt
